KFSPTS-20244 upgrade to the 11-12 version of financials
CU-CommunityApps/cu-kfs pull request #1062
Opened 2020-12-02 14:33 UTC by jhulslander

2020-12-03 15:04 UTC, db483 requested changes
Changes look good. There is one comment that should be updated to the correct version of financials. I think it would be good if the PR title was also updated to use the full version date 11-12-20202. Thank you

2020-12-03 15:04 UTC, db483 commented on src/main/java/edu/cornell/kfs/sys/service/impl/CuGeneralLedgerPendingEntryServiceImpl.java
> +     * With the 11/20/2020 patch, this function was removed from GeneralLedgerPendingEntryServiceImpl,
should this version be 11/12/2020?

2020-12-03 18:47 UTC, jhulslander commented
retest this please

2020-12-03 21:00 UTC, jhulslander commented
I've updated the comment as suggested

2020-12-04 01:20 UTC, chadbower commented on src/main/java/edu/cornell/kfs/sys/service/impl/CuGeneralLedgerPendingEntryServiceImpl.java
> +     * With the 11/20/2020 patch, this function was removed from GeneralLedgerPendingEntryServiceImpl,
please retest this

2020-12-04 01:22 UTC, chadbower commented on src/main/java/edu/cornell/kfs/sys/service/impl/CuGeneralLedgerPendingEntryServiceImpl.java
> +     * With the 11/20/2020 patch, this function was removed from GeneralLedgerPendingEntryServiceImpl,
test this please

2020-12-04 01:23 UTC, chadbower commented
test this please

2020-12-04 01:28 UTC, chadbower commented on src/main/java/edu/cornell/kfs/sys/service/impl/CuGeneralLedgerPendingEntryServiceImpl.java
> +     * With the 11/20/2020 patch, this function was removed from GeneralLedgerPendingEntryServiceImpl,
retest this please

2020-12-04 12:43 UTC, jhulslander commented
retest this please

2020-12-04 13:10 UTC, chadbower commented
retest this please

2020-12-04 13:14 UTC, cujenkins commented
Jenkins get hub plugin test

2020-12-04 13:41 UTC, jhulslander commented
retest this please

2020-12-04 13:47 UTC, jhulslander commented
retest this please

2020-12-04 14:24 UTC, jhulslander commented
this is ready for review again, but the details URL isn't working correct yet

2020-12-04 15:06 UTC, db483 approved these changes
Changes look good.

2020-12-04 15:19 UTC, chadbower commented
retest this please

2020-12-04 16:48 UTC, merged