KFSPTS-18904 remove PaymentWorksFormModeService
CU-CommunityApps/cu-kfs pull request #1074
Opened 2020-12-18 20:41 UTC by jhulslander

2020-12-23 15:05 UTC, db483 requested changes
Changes look good, I only had some small suggestions for improvements. I was also wondering if the commit message should be a bit more specific about the cleanup done rather than just "remove PaymentWorksFormModeService" (PR title)?

Thank you!

2020-12-23 15:22 UTC, jhulslander commented on src/test/java/edu/cornell/kfs/pmw/batch/businessobject/PaymentWorksVendorTest.java
> +    private void assertRestringFieldExists(String toStringValue, String searchField) {
nope, typo, how about assertRestrictedFieldFormattedCorrectly

2020-12-23 15:26 UTC, jhulslander commented on src/test/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksNewVendorPayeeAchServiceImplTest.java
>      void testIsUsAchBankForeignFormUsBank() {
good catch, there were a bunch of test functions that needed renamed here

2020-12-23 15:28 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/pmw/batch/businessobject/PaymentWorksVendor.java
> +    private String buildToStringAppender(String fieldValue) {
Thanks, I switched to buildRestrictedFieldPrintableValue

2020-12-23 15:37 UTC, jhulslander commented
this is ready for review again

2021-01-04 09:32 UTC, db483 approved these changes
Changes look good.

2021-01-04 09:33 UTC, merged