KFSPTS-17867 Implement retries for failed ACH Extract rows
CU-CommunityApps/cu-kfs pull request #1091
Opened 2021-02-04 10:11 UTC by db483

2021-02-05 15:19 UTC, ajd299 requested changes
Please see my feedback, note that many of the changes suggested are optional.

2021-02-08 09:40 UTC, db483 commented on src/main/java/edu/cornell/kfs/pdp/batch/PayeeACHAccountExtractReportData.java
> +        achAccountExtractFileResults = new ArrayList<PayeeACHAccountExtractFileResult>();
updated

2021-02-08 09:41 UTC, db483 commented on src/main/java/edu/cornell/kfs/pdp/batch/PayeeACHAccountExtractResult.java
> +        successEntries = new ArrayList<PayeeACHAccountExtractDetail>();
updated

2021-02-08 09:41 UTC, db483 commented on src/main/java/edu/cornell/kfs/pdp/batch/PayeeACHAccountExtractRetryResult.java
> +public class PayeeACHAccountExtractRetryResult extends PayeeACHAccountExtractResult{
updated

2021-02-08 09:48 UTC, db483 commented on src/main/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountExtractReportServiceImpl.java
> +    }
I moved the code to CuBatchFileUtils. I created https://jira.cornell.edu/browse/KFSPTS-20973 to update RassReportServiceImpl.java

2021-02-08 10:54 UTC, db483 commented on src/main/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountExtractReportServiceImpl.java
> +            for (PayeeACHAccountExtractDetail achDetail : processingResult.getErrorEntries().keySet().stream().sorted((o1,o2)-> o1.getId().compareTo(o2.getId())).collect(Collectors.toList())) {
updated

2021-02-08 11:05 UTC, db483 commented on src/main/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountExtractServiceImpl.java
> +    private void loadACHBatchDetailFiles(PayeeACHAccountExtractReportData achAccountExtractReportData){
updated

2021-02-08 11:05 UTC, db483 commented on src/main/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountExtractServiceImpl.java
> +        List<String> errors = new ArrayList<String>();
updated

2021-02-08 11:06 UTC, db483 commented on src/main/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountExtractServiceImpl.java
> +        List<PayeeACHAccountExtractDetail> sortedAchDetailsEligibleForRetry = new ArrayList<PayeeACHAccountExtractDetail>();
updated

2021-02-08 11:07 UTC, db483 commented on src/main/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountExtractServiceImpl.java
> +        sortedAchDetailsEligibleForRetry = achDetailsEligibleForRetry.stream().sorted((o1, o2) -> o1.getId().compareTo(o2.getId()))
updated

2021-02-08 11:08 UTC, db483 commented on src/main/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountExtractServiceImpl.java
> +        return Integer.valueOf(parameterService.getParameterValueAsString(PayeeACHAccountExtractStep.class, CUPdpParameterConstants.MAX_ACH_ACCT_EXTRACT_RETRY));
updated

2021-02-08 11:08 UTC, db483 commented on src/main/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountExtractServiceImpl.java
> +    private void storeACHAccountExtractDetailForRetry(PayeeACHAccountExtractDetail achDetail, String status) {
updated

2021-02-08 11:09 UTC, db483 commented on src/main/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountExtractServiceImpl.java
> +        achDetail.setStatus( CUPdpConstants.PayeeAchAccountExtractStatuses.OPEN);
removed

2021-02-08 11:09 UTC, db483 commented on src/main/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountExtractServiceImpl.java
> +        List<PayeeACHAccountExtractDetail> persistedPayeeACHAccountExtractDetails = new ArrayList<PayeeACHAccountExtractDetail>();
updated

2021-02-08 11:10 UTC, db483 commented on src/test/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountExtractServiceImplTest.java
> +    private DateTimeService createMockDateTimeService() throws Exception {
removed

2021-02-08 11:10 UTC, db483 commented on src/test/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountExtractServiceImplTest.java
> +    private PayeeACHAccountExtractReportService createMockPayeeACHAccountExtractReportService() throws Exception {
removed

2021-02-08 17:29 UTC, db483 commented
I've added the requested changes but NOT ready yet.

2021-02-09 16:51 UTC, db483 commented
This is ready for review.

2021-02-09 21:31 UTC, ajd299 requested changes
One more small suggestion

2021-02-10 09:26 UTC, db483 commented on src/main/java/edu/cornell/kfs/pdp/batch/PayeeACHAccountExtractResult.java
> +        errorEntries = new HashMap<PayeeACHAccountExtractDetail, List<String>>();
updated

2021-02-10 14:36 UTC, ajd299 approved these changes
Code looks good, merging

2021-02-10 14:38 UTC, merged