KFSPTS-20881: Upgrade to the 01-14-2021 version of financials
CU-CommunityApps/cu-kfs pull request #1092
Opened 2021-02-08 12:14 UTC by nkimble

2021-02-10 12:19 UTC, db483 requested changes
Hi Nancy, 

Changes look good but I have some questions:
- IdentityManagementPersonDocument.java - can this be removed from our overlays?
- should these files have the license headers updated:
-- purapTypes.xsd
-- b2bPunchOutOrderDigesterRules.xml
-- paymentDigesterRules.xml

We seem to have license headers on a lost of xml files that should be either removed or updated. I don't think this should be done as part of this work but rather as a separate cleanup task.

Thank you.

2021-02-10 16:32 UTC, nkimble commented on src/main/java/org/kuali/kfs/kim/document/IdentityManagementPersonDocument.java
> +            setIfRolesEditable();
removed.

2021-02-10 16:49 UTC, nkimble commented
Per our off-line discussion, JIRA KFSPTS-21015 was created to deal with the larger license header issue.
This is ready to be reviewed again.

2021-02-11 11:59 UTC, db483 approved these changes
Changes look good. This can be merged when we are ready to move to DEV.

2021-02-11 15:05 UTC, merged