KFSPTS-20851 adding webservice to KFS to support einvoice pagination
CU-CommunityApps/cu-kfs pull request #1105
Opened 2021-04-16 16:56 UTC by jhulslander

2021-04-20 17:58 UTC, ajd299 requested changes

2021-04-23 12:23 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/module/purap/rest/resource/CuEinvoiceApiResource.java
> +        //String singleQuote = "'";
yes

2021-04-23 12:24 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/module/purap/rest/resource/CuEinvoiceApiResource.java
> +        String vendorList =  sb.toString();
yes, I will switch

2021-04-23 17:37 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/module/purap/dataaccess/impl/CuEinvoiceDaoOjb.java
> +        LOG.debug("buildSQl, generated SQL: " + sql);
Yes, I think it is helpful, it is a debug log statement, so it won't normally print

2021-04-26 19:48 UTC, ajd299 requested changes

2021-04-26 20:00 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/module/purap/dataaccess/CuEinvoiceDao.java
> +    List<String> getFilteredVendorNumbers(String searchCritiera);
ok

2021-04-26 20:00 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/module/purap/dataaccess/impl/CuEinvoiceDaoOjb.java
> +    public List<String> getFilteredVendorNumbers(String searchCritiera) {
ok

2021-04-26 20:01 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/module/purap/dataaccess/impl/CuEinvoiceDaoOjb.java
> +    protected ResultSet queryVendors(String searchCritiera) {
ok

2021-04-26 20:02 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/module/purap/dataaccess/impl/CuEinvoiceDaoOjb.java
> +            String formattedSearchCriteria = KFSConstants.PERCENTAGE_SIGN +  StringUtils.upperCase(searchCritiera).trim() + KFSConstants.PERCENTAGE_SIGN;
ok

2021-04-26 20:04 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/module/purap/dataaccess/impl/CuEinvoiceDaoOjb.java
> +    protected String buildSQl() {
how about buildParameterizedVendorNumberQueryByVendorNameAndDunsNumber

2021-04-26 20:05 UTC, jhulslander commented on src/test/java/edu/cornell/kfs/module/purap/rest/resource/CuEinvoiceApiResourceTest.java
> +    void setUp() throws Exception {
nope, I shall remove

2021-04-26 20:07 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/module/purap/rest/resource/CuEinvoiceApiResource.java
> +        LOG.debug("getVendorNumbersSearchCriteria, searchcriteria: " + searchcriteria);
ok

2021-04-29 18:52 UTC, ajd299 commented
Code looks good, ready to merge once API is finalized

2021-05-03 20:59 UTC, ajd299 approved these changes

2021-05-03 20:59 UTC, merged