KFSPTS-21519 making adding and editing a PAAT document through batch job transactional
CU-CommunityApps/cu-kfs pull request #1117
Opened 2021-05-21 18:40 UTC by jhulslander

I moved code from PayeeACHAccountExtractServiceImpl to the new service PayeeACHAccountDocumentServiceImpl to make  addACHAccount and updateACHAccountIfNecessary.  To avoid adding extra complications to this work, I didn't do "clean code" refactors.  If there are changes you think should be made now, please let me know

2021-05-21 19:12 UTC, jhulslander commented
@cah292 , this is a follow up to my original PR for this user story

2021-05-21 21:04 UTC, cah292 requested changes
I noticed a few areas that may need some minor updates, but other than that the changes look good. I'm also okay with deferring more detailed refactoring of the new service to a later PR, given that this PR is largely just moving the affected code from one class to another.

2021-05-24 13:33 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountDocumentServiceImpl.java
> +    @Transactional
ah, I see what you mean, in RassUpdateServiceImpl the annotation is @Transactional(propagation = Propagation.REQUIRES_NEW) ..... is that what I need to do here?

2021-05-24 13:35 UTC, jhulslander commented on src/test/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountExtractServiceImplTest.java
> +        Mockito.doNothing().when(payeeACHAccountDocumentService).addNote(Mockito.any(), Mockito.anyString());
I am able to run PayeeACHAccountExtractServiceImplTest locally as it's own test.  Springcontext is not instantiated.  Do you need me to look at something else here?

2021-05-24 13:40 UTC, cah292 commented on src/main/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountDocumentServiceImpl.java
> +    @Transactional
Yes, please update the annotations to use the Propagation.REQUIRES_NEW setting. Thanks.

2021-05-24 13:43 UTC, cah292 commented on src/test/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountExtractServiceImplTest.java
> +        Mockito.doNothing().when(payeeACHAccountDocumentService).addNote(Mockito.any(), Mockito.anyString());
If the test is working fine when you run it locally, then Mockito.spy() must be properly handling the situation that I thought would have caused issues. Given that, I'm fine with the current state of the rewritten test class. Thanks for checking.

2021-05-24 15:37 UTC, jhulslander commented
this is ready for review again

2021-05-24 16:00 UTC, cah292 reviewed
Revised changes look good, will merge once the unit tests pass.

2021-05-24 16:07 UTC, cah292 approved these changes
Changes look good, and unit tests pass. Merging.

2021-05-24 16:07 UTC, merged