KFSPTS-15376 add payment works vendor to purge process
CU-CommunityApps/cu-kfs pull request #1148
Opened 2021-07-15 12:00 UTC by jhulslander

This is not review and not ready to be merged

2021-07-20 19:17 UTC, ajd299 requested changes
I have completed the initial review and have a view suggestions/questions

2021-07-20 19:43 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/pmw/batch/PaymentWorksConstants.java
> +
nope, I shall remove

2021-07-20 19:43 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/pmw/batch/PaymentWorksConstants.java
> +        public static final String PMW_VENDOR_REQUESTID = "pmwVendorRequestId";
sure

2021-07-20 19:44 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/pmw/batch/PaymentWorksConstants.java
> +        public static final String REQUESTING_COMPANY_LEGAL_FIRSTNAME = "requestingCompanyLegalFirstName";
OK

2021-07-20 19:45 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/pmw/batch/PaymentWorksConstants.java
> +        public static final String REQUESTING_COMPANY_LEGAL_LASTNAME = "requestingCompanyLegalLastName";
ok

2021-07-20 19:46 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/pmw/batch/businessobject/PaymentWorksVendor.java
> +public class PaymentWorksVendor extends PersistableBusinessObjectBase implements Serializable, PurgableBusinessObjectInterface{
ok

2021-07-20 19:50 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/sys/batch/service/impl/PaymentWorksVendorLookupCriteriaPurgeServiceImpl.java
> +        */
oh, thanks for noticing, I forgot to clean up original impl stuff

2021-07-20 19:51 UTC, jhulslander commented on src/test/java/edu/cornell/kfs/pmw/batch/businessobject/PaymentWorksVendorTest.java
> +    public void assertpurgetRecordingStringContains(String purgeRecordingString, String searchString) {
OK

2021-07-20 19:52 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/sys/batch/service/impl/PaymentWorksVendorLookupCriteriaPurgeServiceImpl.java
> +    private void addPaymentWorksRequestStatusToCriteria( Criteria lookupCriteria, String requestStatus) {
this function was removed

2021-07-20 19:52 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/sys/batch/service/impl/PaymentWorksVendorLookupCriteriaPurgeServiceImpl.java
> +    private void addTransactionTypeToCriteria( Criteria lookupCriteria, String transactionType) {
this function was removed

2021-07-20 20:33 UTC, jhulslander commented
I have made a number of changes based on the comments above, this is ready for review again

2021-07-21 15:44 UTC, ajd299 commented
The code looks well thought out and carefully crafted. Merging

2021-07-21 15:45 UTC, ajd299 approved these changes

2021-07-21 15:45 UTC, merged