KFSPTS-21715 add Security Request wizard
CU-CommunityApps/cu-kfs pull request #1160
Opened 2021-08-11 15:58 UTC by db483

2021-08-12 16:15 UTC, cah292 requested changes
I found a few minor items that would be good to clean up. Other than that, the changes look good.

2021-08-13 11:20 UTC, db483 commented on src/main/java/edu/cornell/kfs/ksr/service/impl/SecurityRequestDocumentServiceImpl.java
> +        hashMap.put("active", true);
updated

2021-08-13 11:20 UTC, db483 commented on src/main/java/edu/cornell/kfs/ksr/web/struts/SecurityRequestWizardForm.java
> +     * @see org.kuali.rice.kns.web.struts.form.KualiForm#shouldMethodToCallParameterBeUsed(java.lang.String,
updated

2021-08-13 11:21 UTC, db483 commented on src/main/webapp/WEB-INF/institutional-struts-config.xml
> +    	</action>
This formatting was off so I fixed it. I will undo the change.

2021-08-13 12:36 UTC, db483 commented on src/main/java/edu/cornell/kfs/ksr/web/struts/SecurityRequestWizardForm.java
> +	public void setSecurityGroups(List<SecurityGroup> securityGroups) {
updated

2021-08-13 12:37 UTC, db483 commented
I added the requested changes and this is ready for review again.

2021-08-13 13:01 UTC, cah292 approved these changes
Changes look good, unit tests pass, and the SQL changes are also ready. One quick note: KFS already has its own constants for the "active" property name, but I'm okay with moving these changes forward as-is and we can clean up the "active" property constants in a future user story.

Merging.

2021-08-13 13:02 UTC, merged