KFSPTS-22704 Reintroduce KFSPTS-13005 billing period fix
CU-CommunityApps/cu-kfs pull request #1202
Opened 2021-10-29 12:35 UTC by jhulslander

2021-10-29 20:38 UTC, cah292 requested changes
I found one very minor item that would be good to clean up. Other than that, the changes look good and they appear to be reintroducing the proper KFSPTS-13005 functionality.

2021-10-29 20:38 UTC, cah292 commented on src/test/java/org/kuali/kfs/module/ar/businessobject/TimeBasedBillingPeriodTest.java
> +    public void testDetermineStartDateByFrequencyNewYeara() {
Minor typo in method name.

2021-11-01 12:32 UTC, jhulslander commented
this is ready for review again

2021-11-01 13:20 UTC, cah292 approved these changes
Changes look good, and unit tests pass. Merging.

2021-11-01 13:21 UTC, merged