KFSPTS-22886 create concur admin screen to get a new request and refresh token
CU-CommunityApps/cu-kfs pull request #1214
Opened 2021-11-15 18:10 UTC by jhulslander

2021-11-19 15:13 UTC, ajd299 commented
Please see my comments. Also, what is the expected behavior if Concur is down?

2021-11-19 15:14 UTC, ajd299 requested changes

2021-11-22 13:14 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/web/struts/ConcurManageRefreshTokenAction.java
> +        String updateRefeshSuccessMessage = MessageFormat.format(
ok

2021-11-22 13:15 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/web/struts/ConcurManageRefreshTokenAction.java
> +        concurTokenForm.setUpdateRefreshTokenMessage(updateRefeshSuccessMessage);
ok

2021-11-22 13:17 UTC, jhulslander commented on src/main/resources/edu/cornell/kfs/concur/cu-spring-concur.xml
> +    </property>
ok

2021-11-22 13:18 UTC, jhulslander commented on src/main/resources/edu/cornell/kfs/concur/web/struts/form/datadictionary/ConcurManageRefreshTokenForm.xml
> +
ok

2021-11-22 13:19 UTC, jhulslander commented on src/main/resources/edu/cornell/kfs/concur/web/struts/form/datadictionary/ConcurManageRefreshTokenForm.xml
> +
ok

2021-11-22 13:19 UTC, jhulslander commented on src/main/webapp/jsp/concur/manageRefreshToken.jsp
> +		<div class="center" style="margin: 30px 0;" ]>
no it shouldn't be there, I am surprised it didn't cause an error, I will remove

2021-11-22 13:21 UTC, jhulslander commented on src/main/webapp/jsp/concur/manageRefreshToken.jsp
> +				<div class="center" style="margin: 30px 0;" ]>
will remove

2021-11-22 14:38 UTC, jhulslander commented
I've made a number of changes based on the feedback.  I've also adjusted the log level to debug on action class logging.  This is ready for review again

2021-11-22 19:12 UTC, ajd299 requested changes
I found one minor format issue. After that I think it is ready to be merged

2021-11-22 21:03 UTC, ajd299 commented
Looks good will merge when unit tests complete

2021-11-22 21:03 UTC, jhulslander commented
I removed the square bracket, this is ready for review again

2021-11-22 21:18 UTC, ajd299 approved these changes

2021-11-22 21:19 UTC, merged