KFSPTS-23544 adding expense v3 allocation processing and expense report validation
CU-CommunityApps/cu-kfs pull request #1249
Opened 2022-01-26 21:30 UTC by jhulslander

this is NOT ready for review

2022-01-28 19:56 UTC, ajd299 requested changes
Code looks good, please see my comments

2022-01-31 12:54 UTC, jhulslander commented on src/test/java/edu/cornell/kfs/concur/eventnotification/rest/jsonObjects/ConcurExpenseDTOJsonTest.java
> +import org.apache.commons.lang3.StringUtils;
nope, I shall remove

2022-01-31 12:55 UTC, jhulslander commented on src/test/java/edu/cornell/kfs/concur/eventnotification/rest/jsonObjects/ConcurExpenseDTOJsonTest.java
> +        validateAllocationDetail(allOcationItem.getSubObject(), null, MARYLAND, MARYLAND);
fixed

2022-01-31 12:57 UTC, jhulslander commented on src/test/java/edu/cornell/kfs/concur/eventnotification/rest/jsonObjects/ConcurExpenseDTOJsonTest.java
> +    }
yes

2022-01-31 13:05 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurExpenseV3ServiceImpl.java
> +        }
ok

2022-01-31 13:06 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurExpenseV3ServiceImpl.java
> +            validateExepsneAllocations(accessToken, processingResults, allocationItems, fullExpenseReport.getId());
ok

2022-01-31 13:07 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurExpenseV3ServiceImpl.java
> +    protected void validateExepsneAllocations(String accessToken, List<ConcurEventNotificationProcessingResultsDTO> processingResults,
ok

2022-01-31 13:07 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurExpenseV3ServiceImpl.java
> +                LOG.info("validateExepsneAllocations, for report " + reportId + " account info: " + info.toString());
ok

2022-01-31 13:21 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurExpenseV3ServiceImpl.java
> +            reportValid = false;
I added reportValid as a parameter to updateStatusInConcur

2022-01-31 13:23 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurExpenseV3ServiceImpl.java
> +    protected ConcurExpenseAllocationV3ListingDTO getConcurExpenseAllocationV3ListingDTO(String accessToken, String reportId, String allocationEndpoint,
removed

2022-01-31 13:49 UTC, jhulslander commented
I have made changes, this is ready for review again

2022-01-31 19:34 UTC, ajd299 approved these changes
Looks Good, Merging

2022-01-31 19:34 UTC, merged