Kfspts 23305 to master
CU-CommunityApps/cu-kfs pull request #1252
Opened 2022-02-07 20:43 UTC by jhulslander

do NOT merge this PR.  Created PR just create a place to review this code.

We will rebuild the kfs-test WAR file with this feature branch, and then do Concur's "test connection". This additional logging should tell us what Concur is is putting in the HTTP request they are sending us.

The goal of this PR is to determine if another developer thinks additional logging may be helpful.

This code won't be merged to master, it is just being used as short term trouble shooting.

2022-02-07 21:08 UTC, jhulslander commented
This PR is failing unit tests because the unit test jenkins job expect kew-to-kfs code, which this code doesn't have.

2022-02-08 12:05 UTC, db483 requested changes
Changes look good, there are just some spelling mistakes.

2022-02-08 12:05 UTC, db483 commented on src/main/java/edu/cornell/kfs/concur/rest/authentication/ConcurAuthenticationFilter.java
> +        logRequst(httpServletRequest);
spelling mistake, should be Request not Requst?

2022-02-08 12:05 UTC, db483 commented on src/main/java/edu/cornell/kfs/concur/rest/authentication/ConcurAuthenticationFilter.java
> +    private void logRequst(HttpServletRequest request) {
code looks good, just has a spelling error in method name and where the method name is used in logging.

2022-02-08 12:05 UTC, db483 commented on src/main/java/edu/cornell/kfs/concur/rest/authentication/ConcurAuthenticationFilter.java
> +            LOG.info("logRequst, this is production, so we aren't dooing this logging.");
'dooing' has spelling mistake.

2022-02-08 15:57 UTC, jhulslander commented
Thanks, I fixed the spelling mistakes, I have a working session scheduled with Tami for Thursday

2022-02-11 14:34 UTC, closed without merging