KFSPTS-25263 create base batch job to upload suppliers to Jaggaer
CU-CommunityApps/cu-kfs pull request #1317
Opened 2022-08-17 20:13 UTC by jhulslander

Please note there is a related non-prod SQL PR.  Don't merge this till both PRs are ready.
There will be a follow up user story to actually create the CSV file, and to make use of the FIPS to ISO mapping service.

2022-08-19 20:38 UTC, ajd299 requested changes
Please see my suggested changes, most of them are just typos

2022-08-22 12:33 UTC, jhulslander commented
retest this please

2022-08-22 13:34 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/module/purap/batch/JaggaerGenerateContractPartyCsvStep.java
> +    }
ok

2022-08-22 13:36 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/module/purap/batch/dataaccess/impl/JaggaerUploadDaoJdbc.java
> +            LOG.error("findJaggaerContractParty, had an error finding jaggaer contract partiess: ", e);
ok

2022-08-22 13:37 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/module/purap/batch/dataaccess/impl/JaggaerUploadDaoJdbc.java
> +    private String buildPurchasOrderLimitSubQuery(String processingDate) {
ok

2022-08-22 13:39 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/module/purap/batch/dataaccess/impl/JaggaerUploadDaoJdbc.java
> +        return vendorHeaderId + KFSConstants.DASH + venderDetailId;
ok

2022-08-22 14:57 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/module/purap/batch/service/impl/JaggaerGenerateContractPartyCsvServiceImpl.java
> +    }
ok

2022-08-22 15:04 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/module/purap/businessobject/lookup/JaggaerContractPartyUploadDto.java
> +        builder.append("taxIdentificationNumber", StringUtils.isBlank(taxIdentificationNumber) ? StringUtils.EMPTY : "restrctived tax id number");
switched to Restricted

2022-08-22 15:07 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/vnd/CUVendorConstants.java
> +
nope, not needed, thanks

2022-08-22 15:08 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/vnd/CUVendorConstants.java
> +    public final class FIELD_NAMES {
yeah, it should be static

2022-08-22 15:11 UTC, jhulslander commented on src/test/java/edu/cornell/kfs/module/purap/batch/service/impl/JaggaerGenerateContractPartyCsvServiceImplTest.java
> +        assertEquals(buildVendor1Dto(), actualFirstELement, "The first element shound be vendor 1");
ok

2022-08-22 15:12 UTC, jhulslander commented on src/test/java/edu/cornell/kfs/module/purap/batch/service/impl/JaggaerGenerateContractPartyCsvServiceImplTest.java
> +        JaggaerContractPartyUploadDto actualFourthELement = (JaggaerContractPartyUploadDto) jaggaerUploadDtos.get(3);
ok

2022-08-22 15:12 UTC, jhulslander commented on src/test/java/edu/cornell/kfs/module/purap/batch/service/impl/JaggaerGenerateContractPartyCsvServiceImplTest.java
> +        assertEquals(buildVendor2WithTaxIdDto(), actualFourthELement, "THe fourth elemeent should be vendor 2");
ok

2022-08-22 15:13 UTC, jhulslander commented on src/test/java/edu/cornell/kfs/module/purap/batch/service/impl/JaggaerGenerateContractPartyCsvServiceImplTest.java
> +                Arguments.of(buildVendor2WithTaxIdDto(), "taxIdentificationNumber=restrctived tax id number"),
restricted

2022-08-22 19:23 UTC, jhulslander commented
I've made the changes suggested, I also discovered a problem with the SQL that I have corrected, in doing so I simplified and reduced some duplication in how the SQL is generated in JaggaerUploadDaoJdbc.

This is ready for review again

2022-08-23 18:46 UTC, ajd299 approved these changes
Code looks good, merging

2022-08-23 18:47 UTC, merged