KFSPTS-25918: Adjust ISO FIPS Service to only return mapped value when…
CU-CommunityApps/cu-kfs pull request #1329
Opened 2022-09-12 12:00 UTC by nkimble

… ALL (ISO Country, FIPS Country, Mapping) are Active. Batch job testISOFIPSConversionMappingsJob created to verify mapping conversion service against actual database tables.

2022-09-12 12:04 UTC, nkimble commented
retest this please

2022-09-12 15:33 UTC, jhulslander requested changes
Code changes look good for the most part, I found a few things to consider

2022-09-12 15:33 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/sys/service/impl/ISOFIPSConversionServiceImpl.java
>          if (mappingsFound.isEmpty()) {
instead of doing these .isEmpty checks you could use CollectionUtils, that would give you a null check for free

2022-09-13 16:54 UTC, jhulslander approved these changes
PR looks good, unit tests pass, I shall merge

2022-09-13 16:56 UTC, merged