KFSPTS-22328 create concur event notification v2 results report
CU-CommunityApps/cu-kfs pull request #1332
Opened 2022-09-19 20:31 UTC by jhulslander

this is NOT ready for review yet

2022-09-26 14:18 UTC, db483 requested changes
Changes look good but I had some small suggestions for improvement.

2022-10-03 18:12 UTC, jhulslander commented on src/main/resources/CU-ApplicationResources.properties
> +concur.event.v2.processing.report.file.name=Concurn_Event_Notification_V2_Processing_Results_
ok

2022-10-03 18:15 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurEventNotificationV2ReportServiceImpl.java
> +        boolean htmlMessage = false;
I will do the direct method

2022-10-03 18:25 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurEventNotificationV2ReportServiceImpl.java
> +        BodyMailMessage message = new BodyMailMessage();
sure

2022-10-04 09:35 UTC, db483 commented on src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurEventNotificationV2ReportServiceImpl.java
> +            LOG.debug("sendEmail, the email budy: " + body);
I think this should be "the email body"

2022-10-04 09:37 UTC, db483 commented
Changes look good. There is just one misspelling to be corrected. Thank you.

2022-10-04 11:44 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurEventNotificationV2ReportServiceImpl.java
> +            LOG.debug("sendEmail, the email budy: " + body);
ok

2022-10-04 11:53 UTC, jhulslander commented
I fixed the typo .... please hold off on merging this PR though.  I am waiting for Tami to create some invalid account requests in Concur and for Tami to give feedback.

2022-10-04 11:56 UTC, db483 commented
Sounds good. Thank you.

2022-10-12 19:23 UTC, jhulslander commented
I have made some changes based on feedback from Tami and Cathy.  This is ready for review again

2022-10-14 15:33 UTC, db483 approved these changes
Changes look good.

2022-10-14 15:33 UTC, merged