KFSPTS-25323 upgrade to the 4/13/2022 version of financials
CU-CommunityApps/cu-kfs pull request #1388
Opened 2023-01-24 08:24 UTC by db483

2023-01-30 16:20 UTC, db483 commented
retest this please

2023-01-30 17:54 UTC, db483 commented
retest this please

2023-02-01 22:54 UTC, cah292 reviewed
I'm still reviewing the changes, but I did want to bring up one item in the meantime.

2023-02-02 08:42 UTC, db483 commented on src/main/java/edu/cornell/kfs/fp/document/CuDisbursementVoucherDocument.java
>                  this.getDvPayeeDetail().setDisbVchrNonresidentPaymentCode(false);
Thank you for catching this. I will clean this up.

2023-02-02 11:02 UTC, db483 commented on src/main/java/edu/cornell/kfs/fp/document/CuDisbursementVoucherDocument.java
>                  this.getDvPayeeDetail().setDisbVchrNonresidentPaymentCode(false);
I made updates to remove references to `this` that are not needed. For `final` local variables, did you notice some instances that were updated in base code but not in our extension? Or is this s suggestion to update all local variables to `final`? Thank you

2023-02-02 14:31 UTC, cah292 commented on src/main/java/edu/cornell/kfs/fp/document/CuDisbursementVoucherDocument.java
>                  this.getDvPayeeDetail().setDisbVchrNonresidentPaymentCode(false);
Thanks for the cleanup. I had noticed some method parameters that were missing the `final` keyword, but I don't recall whether they were on CU-specific methods or overridden methods.

I'm fine with deferring the rest of the `this` and `final` cleanup to future stories, especially if we end up deciding to add such changes to our regular coding standards. I'll add a bookclub agenda item for discussing with the team.

2023-02-02 21:17 UTC, cah292 requested changes
Changes look good overall, but I noticed a few more items to be addressed:

1. For consistency with base code, the method `CuElectronicInvoiceHelperServiceImpl.createPaymentRequest()` may need to be adjusted to use a Spring-injected PersonService instead of calling SpringContext directly. I realize that the `personService` field is a private one, so you may need to add a related field to the subclass and override the setter if you want to avoid introducing an overlay. We should also report this to KualiCo if you think the field's visibility should be increased.
2. The method `CuVendorRuleBase.validateParentVendorTaxNumber()` should add the "active" flag to the appropriate criteria, for consistency with the changes in base code.

2023-02-03 08:47 UTC, db483 commented
Thank you for your review Chad. I made the requested changes and reported to KualiCo the field visibility increase: KFSPTS-27415.

2023-02-03 14:25 UTC, cah292 commented
@db483,

You mentioned that you made the requested changes, but in this PR I'm not seeing any new changes to the files I had mentioned. Can you please confirm if your latest changes have been committed yet? Thanks.

2023-02-03 14:29 UTC, db483 commented
It looks like I forgot to push the changes. they should be available now. Thank you.

2023-02-03 18:16 UTC, cah292 approved these changes
Changes look good, unit tests pass, my concerns have been addressed and the related PRs are also ready. Merging.

2023-02-03 18:17 UTC, merged