KFSPTS-27124 Concur Event Notification V2 Renaming
CU-CommunityApps/cu-kfs pull request #1414
Opened 2023-03-01 17:06 UTC by ajd299

2023-03-01 21:54 UTC, ajd299 commented
retest this please

2023-03-07 20:07 UTC, jhulslander requested changes

2023-03-07 20:07 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurEventNotificationApiServiceImpl.java
> +public class ConcurEventNotificationApiServiceImpl implements ConcurEventNotificationApiService {
Since this service is used to call Concur webservice endpoints, I think it should have Webservice in the name

2023-03-07 20:07 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/batch/service/ConcurEventNotificationApiService.java
> +public interface ConcurEventNotificationApiService {
since this interface defines functions to call Concur Webservices, I think Webservice should be in the interface name

2023-03-07 20:08 UTC, jhulslander commented
Changes look good for the most part, I just had a couple of notes

2023-03-09 18:31 UTC, ajd299 commented
I renamed ConcurEventNotificationApiService to ConcurEventNotificationWebserviceService

2023-03-09 18:51 UTC, ajd299 commented
Here are 3 candidates, Jay/Chad let us know your thoughts on what is most appropriate.
- `ConcurEventNotificationWebserviceService`
- `ConcurEventNotificationWebServiceCallsService`
- `ConcurEventNotificationWebApiService`

2023-03-09 19:15 UTC, cah292 commented
@ajd299 I prefer `ConcurEventNotificationWebApiService` the most; it describes the functionality accurately while still being fairly concise.

My second-favorite would be `ConcurEventNotificationWebServiceCallsService`, since that's consistent with the web-invoking class in our PaymentWorks integration.

2023-03-09 19:21 UTC, ajd299 commented
I think ConcurEventNotificationWebApiService as Web API is synonymous to Web Service. I will work on changing it to ConcurEventNotificationWebApiService. @jhulslander are you good with ConcurEventNotificationWebApiService?

2023-03-10 17:32 UTC, jhulslander approved these changes
CHanges look good, unit tests pass, I shall merge

2023-03-10 17:32 UTC, merged