KFSPTS-28175: Convert AccountReversion, AccountReversionDetail, and ReversionCategory to new lookup-inquiry framework and using new framework collections. Required creation of new docType ARVC.
CU-CommunityApps/cu-kfs pull request #1448
Opened 2023-04-18 19:48 UTC by nkimble

2023-04-21 16:40 UTC, nkimble commented
Related SQL PR #1232 must be merged at the same time

2023-04-21 16:41 UTC, nkimble commented
retest this please

2023-04-24 20:26 UTC, cah292 requested changes
Changes look good overall, though I did find some areas that could use further revisions.

2023-04-24 20:26 UTC, cah292 commented on src/main/resources/edu/cornell/kfs/coa/document/datadictionary/ReversionCategoryMaintenanceDocument.xml
> +                <bean parent="MaintainableFieldDefinition" p:name="active" p:defaultValue="true" p:required="true" p:newLookup="true"/>
Can these fields omit the `newLookup` setting? It doesn't look like these four fields are linking to any other BOs.

2023-05-10 13:07 UTC, nkimble commented on src/main/resources/edu/cornell/kfs/coa/businessobject/datadictionary/AccountReversion.xml
> +    <bean id="AccountReversion-universityFiscalYear-fieldDefinition"
I have revert to using the inline FieldDefinition notation per your request. 
I was following the example of how KualiCo converted collections to the new framework using that -fieldDefiniton setup as they never provide explanations of why they do what they do. We will need to keep in mind that we may have to revert back to that notation should they start to depend upon it in base code for some reason.

2023-05-10 13:07 UTC, nkimble commented on src/main/resources/edu/cornell/kfs/coa/businessobject/datadictionary/AccountReversionDetail.xml
> +    <bean id="AccountReversionDetail-accountReversionCategoryCode-fieldDefinition"
Adjusted the code per your request.

2023-05-10 13:13 UTC, nkimble commented
Requested changes have been made. Unit tests are running. This is ready to be reviewed again. Please also re-review the associated SQL for this code PR as I fixed a SQL issue identified during that SQL's PR review.

2023-05-10 21:18 UTC, cah292 reviewed
I noticed a couple more items that may need to be cleaned up, but overall the latest revisions look good.

2023-05-12 17:35 UTC, nkimble commented on src/main/java/edu/cornell/kfs/coa/businessobject/AccountReversion.java
> +    public String getAccountReversionViewer() {
Changed back.

2023-05-12 17:35 UTC, nkimble commented on src/main/resources/edu/cornell/kfs/coa/businessobject/datadictionary/AccountReversion.xml
> +    <import resource="classpath:edu/cornell/kfs/coa/businessobject/datadictionary/AccountReversionDetail.xml"/>
removed import.

2023-05-12 19:09 UTC, cah292 approved these changes
Changes look good, unit tests pass, my concerns have been addressed and the related SQL PR is also ready. (We decided that these changes can move ahead in advance of the documentation revisions.) If we discover that further cleanup is needed, we can handle that in a subsequent ticket.

Merging.

2023-05-12 19:11 UTC, merged