KFSPTS-29497 Improve handling of ISO 20022 ACH dates and Check forms
CU-CommunityApps/cu-kfs pull request #1497
Opened 2023-09-11 17:55 UTC by cah292

There are PRs for this in both cu-kfs and nonprod-sql. Please make sure both are good to go before merging.

This PR makes the following improvements to the ISO 20022 extraction:

* Modifies the execution/extraction date on the ACH file to be 1 day later than the current date.
* Modifies the Check file so that the "Forms Code" on the Check entries is now derived from a parameter, rather than being hard-coded.

2023-09-11 17:58 UTC, cah292 commented
NOTE: I don't think this will have merge conflicts with the proposed #1496 changes, but we won't know for sure until that PR or this PR gets merged.

2023-09-13 16:31 UTC, ajd299 requested changes
Only possible suggestion

2023-09-14 19:53 UTC, cah292 commented on src/main/java/org/kuali/kfs/pdp/batch/service/impl/Iso20022FormatExtractor.java
> +        }
I've updated this to use a separate method like you suggested.

2023-09-14 19:55 UTC, cah292 commented
I've updated the code based on the initial feedback. This is ready for review again.

2023-09-14 20:41 UTC, ajd299 approved these changes
Looks good, merging

2023-09-14 20:41 UTC, merged