KFSPTS-29123 implement JaggaerUploadFileServiceImplTest.java
CU-CommunityApps/cu-kfs pull request #1498
Opened 2023-09-13 16:13 UTC by jhulslander

2023-09-14 20:37 UTC, ajd299 requested changes
I found a few things that could be changed

2023-09-14 20:37 UTC, ajd299 requested changes
I found a few things that could be changed

2023-09-15 11:37 UTC, jhulslander commented on src/test/java/edu/cornell/kfs/module/purap/CuPurapTestConstants.java
> +        private JaggaerMockServerCongiration(int statusCode, String responseMessage, String[] logSearchStrings) {
ok

2023-09-15 11:38 UTC, jhulslander commented on src/test/java/edu/cornell/kfs/module/purap/CuPurapTestConstants.java
> +    private static final String NUMBER_OF_ATTTEMPTS_MESSAGE_FORMAT = "processUnsuccessfulResponse, attempt number %s, had an unsuccessful webservice call";
ok

2023-09-15 11:40 UTC, jhulslander commented on src/test/java/edu/cornell/kfs/module/purap/CuPurapTestConstants.java
> +        DO_NOT_RUN(606, "conition to not run", new String[]{UPLOAD_TURNED_OFF_MESSAGE}),
ok

2023-09-15 11:42 UTC, jhulslander commented on src/test/java/edu/cornell/kfs/module/purap/batch/service/impl/MockJaggaerUploadSuppliersEndpoint.java
> +            throws HttpException, IOException {
Yes, see MockServiceEndpointBase.processRequest

2023-09-15 11:46 UTC, jhulslander commented on src/test/java/edu/cornell/kfs/module/purap/batch/service/impl/MockJaggaerUploadSuppliersEndpoint.java
> +    private CUMarshalService cuMarshalService;
yeah, I can .... I thought we were doing that to parameter variables that don't change

2023-09-15 11:48 UTC, jhulslander commented on src/test/java/edu/cornell/kfs/module/purap/batch/service/impl/MockJaggaerUploadSuppliersEndpoint.java
> +    private String marshalSynchMessageToString(SupplierSyncMessage supplierSyncMessage) {
ok

2023-09-15 11:49 UTC, jhulslander commented on src/test/java/edu/cornell/kfs/module/purap/batch/service/impl/MockJaggaerUploadSuppliersEndpoint.java
> +        this.jaggaerMockServerCongiration = jaggaerMockServerCongiration;
ok

2023-09-15 12:29 UTC, jhulslander commented
this is ready for review again

2023-09-15 15:16 UTC, ajd299 approved these changes
looks good, merging

2023-09-15 15:16 UTC, merged