KFSPTS-24382 Validate Room Exists in Building
CU-CommunityApps/cu-kfs pull request #1517
Opened 2023-10-26 17:02 UTC by ajd299

2023-10-30 15:13 UTC, jhulslander requested changes
I found a few things to consider

2023-10-30 15:13 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/module/cam/rest/resource/CuCapAssetInventoryApiResource.java
> +                String errorMessage = String.format("Invalid Room #%s for Building Code %s", roomNumber, buildingCode);
should this be in a resources file?

2023-10-30 15:13 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/module/cam/rest/resource/CuCapAssetInventoryApiResource.java
> +            responseErrorMessage += ": " + errorMessage;
should ": " be moved to a constant?

2023-10-30 15:13 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/module/cam/rest/resource/CuCapAssetInventoryApiResource.java
> +            if(!validateBuildingRoomCombination(buildingCode, roomNumber)) {
should there be a validation for the building number too?

2023-10-30 15:13 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/module/cam/rest/resource/CuCapAssetInventoryApiResource.java
> +        return respondBadRequest("");
you could use SprintUtils.space rather than creating a new String here

2023-11-01 15:40 UTC, ajd299 commented
I tried to address all of your feedback. Please see my latest commits

2023-11-02 17:51 UTC, jhulslander approved these changes
My concerns have been addressed, and the unit tests pass, I shall merge

2023-11-02 17:51 UTC, merged