KFSPTS-30483 remove ehCache - Redis customiztion
CU-CommunityApps/cu-kfs pull request #1541
Opened 2024-01-12 20:07 UTC by jhulslander

This PR removes the Cornell customization of ehCache - Redis

Do not merge this PR yet

2024-01-18 09:45 UTC, db483 commented
Changes look good

2024-01-23 16:15 UTC, jhulslander commented
Based on today's meeting this PR can be merged into develop after it passes code review

2024-01-23 18:02 UTC, cah292 requested changes
I noticed one item that should be fixed, but otherwise the changes look good.

2024-01-23 18:02 UTC, cah292 commented on src/main/java/org/kuali/kfs/sys/cache/CacheConfiguration.java
Instead of removing this overlay entirely, I would suggest making the following changes:

1. Replace the contents of this `CacheConfiguration` overlay with the current copy from the 2023-01-25 financials patch in base code.
2. In the `cacheNames()` method, add the CU-specific `MaintenanceUtils.LOCKING_ID_CACHE_NAME` entry to the collection.

2024-01-23 20:19 UTC, jhulslander commented
@cah292 
this is ready for review again

2024-01-23 20:36 UTC, cah292 approved these changes
Changes look good, unit tests pass and my concerns have been addressed.

@jhulslander Do you want me to proceed with merging this to develop now, so that it will be ready in DEV tomorrow? Or do you want me to wait?

2024-01-23 20:43 UTC, jhulslander commented
@cah292  please merge this, I will do the redis instance updates now

2024-01-23 20:48 UTC, cah292 commented
@jhulslander Thanks for the confirmation. Merging now.

2024-01-23 20:48 UTC, merged