KFSPTS-30712 Add SSC Processor Field to IWNT Document
CU-CommunityApps/cu-kfs pull request #1551
Opened 2024-01-31 17:02 UTC by ajd299

2024-02-01 13:26 UTC, nkimble requested changes
I think some of the files for a different user story are included in this PR. Could you please take a look.

2024-02-01 13:26 UTC, nkimble commented on src/main/resources/com/rsmart/kuali/kfs/cr/businessobject/datadictionary/CheckReconciliation.xml
> +              p:attributeName="active" />
Are these changes part of KFSPTS-30132? I don't think this file should be in this PR.

2024-02-01 13:26 UTC, nkimble commented on src/main/resources/com/rsmart/kuali/kfs/cr/document/datadictionary/CheckReconciliationMaintenanceDocument.xml
> +              p:defaultValue="true" />
Are these changes part of KFSPTS-30132? I don't think this file should be in this PR.

2024-02-01 13:26 UTC, nkimble commented on src/main/resources/com/rsmart/kuali/kfs/cr/ojb-cr.xml
> +    	<field-descriptor name="active" column="ACTV_IND" jdbc-type="VARCHAR" conversion="org.kuali.kfs.core.framework.persistence.ojb.conversion.OjbCharBooleanConversion" />
Are these changes part of KFSPTS-30132? I don't think this file should be in this PR.

2024-02-01 14:29 UTC, ajd299 commented
Thanks for catching that I have reversed that commit and it there should no longer be any CheckReconciliation code in this Pull Request

2024-02-01 17:00 UTC, nkimble commented
These code changes look good. 
I did have a question regarding the nonprod-sql changes previously merged on PR 1334 in that repository.

Asking the question: Will we now need (should we have) an index on this new data value since it has been added to the Document Search?

2024-02-01 20:06 UTC, ajd299 commented
Please see https://github.com/CU-CommunityApps/nonprod-sql/pull/1340

2024-02-02 15:06 UTC, nkimble approved these changes
My concerns have been address and related/required SQL changes are also ready. Approving for merge.

2024-02-02 15:07 UTC, merged