KFSPTS-30233 Fix Concur SAE Cash Advance Validation Line Detail False Errors
CU-CommunityApps/cu-kfs pull request #1583
Opened 2024-03-27 19:10 UTC by ajd299

2024-04-02 18:42 UTC, cah292 requested changes
Changes look good overall, though I did find some areas that may need further cleanup.

2024-04-02 18:42 UTC, cah292 commented on src/main/java/edu/cornell/kfs/concur/batch/businessobject/ConcurStandardAccountingExtractDetailLine.java
> +        sb.append(" cashAdvanceAdministratorApprovedCashAdvance: ").append(validationResult.isCashAdvanceApprovedOrApplied());
The string label should be updated to reflect the new property name.

2024-04-02 18:42 UTC, cah292 commented on src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurSaeCreateRequestedCashAdvanceFileValidationServiceImpl.java
> +     * Requested cash advances are either valid if they are either approved by administrator (1) or applied to trip reimbursement (2)
You may want to reword this comment to avoid using the word "either" twice.

2024-04-02 18:42 UTC, cah292 commented on src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurSaeCreateRequestedCashAdvanceFileValidationServiceImpl.java
> +                getConcurStandardAccountingExtractCashAdvanceService().isPreTripCashAdvanceIssuedByCashAdmin(detailFileLine);
This section is calling the `isPreTripCashAdvanceIssuedByCashAdmin()` method twice with the same arguments. Did you mean to replace one of those calls with `isCashAdvanceToBeAppliedToReimbursement()` instead?

2024-04-02 18:42 UTC, cah292 commented on src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractCashAdvanceServiceImpl.java
> +                    || StringUtils.equalsIgnoreCase(saeLine.getCashAdvanceTransactionType(), ConcurConstants.SAE_CASH_ADVANCE_BEING_APPLIED_TO_TRIP_REIMBURSEMENT))) {
Is there a reason why the applied-to-reimbursement check is being added here? Could the caller invoke `isCashAdvanceToBeAppliedToReimbursement()` instead, or does that method's additional `cashAdvanceKeyExists()` verification mess things up?

2024-04-02 18:42 UTC, cah292 commented on src/main/resources/CU-ApplicationResources.properties
> +validation.error.concur.sae.not.cash.admin.approved=SAE cash advance request not approved or applied. Detected Cash Advance Admin Indicator of {0}.
Since you're expanding this error message to include the not-applied case, should the message's key be renamed to reflect that?

2024-04-03 21:12 UTC, cah292 reviewed
I wasn't sure whether this was fully ready for review again, though I went ahead and performed a review of the current follow-up changes. I noticed one minor item that may or may not need updates, but otherwise the revisions look good.

2024-04-03 21:12 UTC, cah292 commented on src/main/java/edu/cornell/kfs/concur/ConcurKeyConstants.java
> +    public static final String CONCUR_SAE_NOT_APPROVED_REQUESTED_CASH_ADVANCE_DATA_LINE = "validation.error.concur.sae.not.approved.or.applied";
Should the name of this constant be updated to reflect the "approved-or-applied" change in the property name?

2024-04-03 23:23 UTC, ajd299 commented
Yes thank you, my internet was down this morning.

2024-04-04 15:03 UTC, ajd299 commented
Ready to be reviewed again.

2024-04-04 16:37 UTC, cah292 approved these changes
Changes look good, unit tests pass and my concerns have been addressed. Merging.

2024-04-04 16:38 UTC, merged