KFSPTS-29347: Upgrade to the 04/19/2023 version of financials.
CU-CommunityApps/cu-kfs pull request #1650
Opened 2024-09-19 19:54 UTC by nkimble

2024-09-24 18:07 UTC, jhulslander commented
retest this please

2024-09-24 18:35 UTC, jhulslander commented
retest this please

2024-09-25 13:47 UTC, db483 requested changes
I am still reviewing the upgrade but I added some notes and some things that might need further attention. Thank you.

2024-09-25 13:47 UTC, db483 commented on src/main/resources/edu/cornell/kfs/module/purap/cu-ojb-purap.xml
> +        <reference-descriptor name="wireTransfer" class-ref="org.kuali.kfs.sys.businessobject.PaymentSourceWireTransfer"
should this be moved up with the other reference-descriptor entries?

2024-10-03 10:31 UTC, db483 commented on pom.xml
> +            <scope>compile</scope>
Should this be 'runtime'?

2024-10-04 08:06 UTC, db483 commented on pom.xml
> +            <scope>compile</scope>
updated

2024-10-04 08:11 UTC, db483 commented on src/main/java/edu/cornell/kfs/module/purap/document/authorization/CuPaymentRequestDocumentPresentationController.java
> -            editModes.add(KfsAuthorizationConstants.TransactionalEditMode.WIRE_ENTRY);
This method call super and base code is adding WIRE_ENTRY when doc in PaymentMethodReview node so this changes should be fine.

2024-10-04 08:43 UTC, db483 commented on src/main/java/edu/cornell/kfs/module/purap/service/impl/CuElectronicInvoiceHelperServiceImpl.java
>                  hasPaymentMethodCode = true;
updated

2024-10-04 08:45 UTC, db483 commented on src/main/java/edu/cornell/kfs/module/purap/service/impl/CuPdpExtractService.java
>      protected void updatePaymentRequest(
updated

2024-10-04 10:42 UTC, db483 commented on src/main/resources/edu/cornell/kfs/sys/businessobject/datadictionary/PaymentMethod.xml
> +    <bean id="PaymentMethod-extension-additionalCreditMemoDataCode" parent="PaymentMethod-extension-additionalCreditMemoDataCode-parentBean"/>
additionalCreditMemoDataCode needs to be added to the inquiry and maintenance screens

2024-10-04 10:52 UTC, db483 commented on src/main/resources/edu/cornell/kfs/sys/businessobject/datadictionary/PaymentMethod.xml
> +    <bean id="PaymentMethod-extension-additionalCreditMemoDataCode" parent="PaymentMethod-extension-additionalCreditMemoDataCode-parentBean"/>
updated

2024-10-04 10:59 UTC, db483 commented on pom.xml
> +            <scope>compile</scope>
needed at compile time

2024-10-08 08:05 UTC, db483 commented on src/main/resources/edu/cornell/kfs/module/purap/cu-ojb-purap.xml
> +        <reference-descriptor name="wireTransfer" class-ref="org.kuali.kfs.sys.businessobject.PaymentSourceWireTransfer"
moved

2024-10-24 18:49 UTC, closed without merging