KFSPTS-33361 add webservice for concur AI project to get account details
CU-CommunityApps/cu-kfs pull request #1675
Opened 2024-12-23 20:22 UTC by jhulslander

2024-12-24 13:26 UTC, db483 requested changes
Changes look good but I found a few things to consider. Thank you.

2025-01-02 19:37 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/rest/resource/ConcurAIResource.java
> +    private Gson gson = new Gson();
ok

2025-01-02 19:37 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/rest/resource/ConcurAIResource.java
> +            String chart = servletRequest.getParameter(KFSPropertyConstants.CHART_OF_ACCOUNTS_CODE);
yes, they should, I will update

2025-01-02 20:25 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/rest/resource/ConcurAIResource.java
> +                return Response.status(Status.BAD_REQUEST.getStatusCode(), ConcurAIConstants.CHART_AND_ACCOUNT_MUST_BE_PROVIDED).build();
thanks, that does look better

2025-01-02 20:27 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/rest/resource/ConcurAIResource.java
> +            return Response.serverError().build();
ok

2025-01-02 20:27 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/rest/resource/ConcurAIResource.java
> +            accountService = SpringContext.getBean(AccountService.class);;
ok

2025-01-02 20:41 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/rest/resource/ConcurAIResource.java
> +            String chart = servletRequest.getParameter(KFSPropertyConstants.CHART_OF_ACCOUNTS_CODE);
further down i added validatePropertyValue() which uses the datadictionary service to get the validation expression for the property.  I think this should meet the need.  Please let me know if you think an alternative approach would be better.

2025-01-02 21:02 UTC, jhulslander commented
This is ready for review again

2025-01-06 13:30 UTC, db483 commented on src/main/java/edu/cornell/kfs/concur/rest/resource/ConcurAIResource.java
> +    private boolean validatePropertyValue(String propertyName, String propertyValue) {
Since this is only validating Account properties should the method name be updated to reflect that? or should the class be added to method params?

2025-01-06 13:36 UTC, db483 commented on src/main/java/edu/cornell/kfs/concur/rest/resource/ConcurAIResource.java
> +            String chart = servletRequest.getParameter(KFSPropertyConstants.CHART_OF_ACCOUNTS_CODE);
Should the validation method also check on the length of the input value?

2025-01-06 15:43 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/rest/resource/ConcurAIResource.java
> +    private boolean validatePropertyValue(String propertyName, String propertyValue) {
I renamed it for account properties

2025-01-06 15:43 UTC, jhulslander commented on src/main/java/edu/cornell/kfs/concur/rest/resource/ConcurAIResource.java
> +            String chart = servletRequest.getParameter(KFSPropertyConstants.CHART_OF_ACCOUNTS_CODE);
OK, I will add a max length check

2025-01-06 16:01 UTC, jhulslander commented
I have made additional changes, this is ready for review again

2025-01-06 16:13 UTC, db483 approved these changes
Changes look good.

2025-01-06 16:14 UTC, merged